name = "Vulkan"
uuid = "9f14b124-c50e-4008-a7d4-969b3a6cd68a"
authors = ["Cédric Belmant", "Simon Danisch"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
VulkanCore = "16167f82-ea26-5cba-b1de-ed6fd5e30a11"

[compat]
DocStringExtensions = "0.8"
MLStyle = "0.4"
VulkanCore = "1.2"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
