module VulkanFixedPointNumbersExt

using Vulkan
using FixedPointNumbers

# No bindings to extend when Vulkan compiled none — see `VulkanCore.HAS_LOADER`.
# `Vk.Format` does not exist then, and an extension that referenced it was the
# last thing on a driverless machine still failing to precompile.
@static if Vulkan.HAS_LOADER


# generated by `ext/generate_formats.jl`.

Vk.Format(::Type{N0f8}) = FORMAT_R8_UNORM
Vk.Format(::Type{Q0f7}) = FORMAT_R8_SNORM
Vk.Format(::Type{N0f16}) = FORMAT_R16_UNORM
Vk.Format(::Type{Q0f15}) = FORMAT_R16_SNORM

Vk.format_type(::Val{FORMAT_R8_SRGB}) = N0f8
Vk.format_type(::Val{FORMAT_R8_UNORM}) = N0f8
Vk.format_type(::Val{FORMAT_R8_SNORM}) = Q0f7
Vk.format_type(::Val{FORMAT_R16_UNORM}) = N0f16
Vk.format_type(::Val{FORMAT_R16_SNORM}) = Q0f15
Vk.format_type(::Val{FORMAT_D16_UNORM}) = N0f16
Vk.format_type(::Val{FORMAT_D16_UNORM_S8_UINT}) = Tuple{N0f16, UInt8}

end # @static if Vulkan.HAS_LOADER

end
