module VulkanFixedPointNumbersStaticArraysCoreExt

using Vulkan
using FixedPointNumbers
using StaticArraysCore: SVector

# generated by `ext/generate_formats.jl`.

Vk.Format(::Type{SVector{2, Q0f7}}) = FORMAT_R8G8_SNORM
Vk.Format(::Type{SVector{3, Q0f7}}) = FORMAT_R8G8B8_SNORM
Vk.Format(::Type{SVector{4, Q0f7}}) = FORMAT_R8G8B8A8_SNORM
Vk.Format(::Type{SVector{2, N0f8}}) = FORMAT_R8G8_UNORM
Vk.Format(::Type{SVector{3, N0f8}}) = FORMAT_R8G8B8_UNORM
Vk.Format(::Type{SVector{4, N0f8}}) = FORMAT_R8G8B8A8_UNORM
Vk.Format(::Type{SVector{2, Q0f15}}) = FORMAT_R16G16_SNORM
Vk.Format(::Type{SVector{3, Q0f15}}) = FORMAT_R16G16B16_SNORM
Vk.Format(::Type{SVector{4, Q0f15}}) = FORMAT_R16G16B16A16_SNORM
Vk.Format(::Type{SVector{2, N0f16}}) = FORMAT_R16G16_UNORM
Vk.Format(::Type{SVector{3, N0f16}}) = FORMAT_R16G16B16_UNORM
Vk.Format(::Type{SVector{4, N0f16}}) = FORMAT_R16G16B16A16_UNORM

Vk.format_type(::Val{FORMAT_R8G8_SNORM}) = SVector{2, Q0f7}
Vk.format_type(::Val{FORMAT_R8G8_UNORM}) = SVector{2, N0f8}
Vk.format_type(::Val{FORMAT_G8B8G8R8_422_UNORM}) = SVector{4, N0f8}
Vk.format_type(::Val{FORMAT_B8G8R8G8_422_UNORM}) = SVector{4, N0f8}
Vk.format_type(::Val{FORMAT_R16G16_SNORM}) = SVector{2, Q0f15}
Vk.format_type(::Val{FORMAT_R16G16_UNORM}) = SVector{2, N0f16}
Vk.format_type(::Val{FORMAT_G16B16G16R16_422_UNORM}) = SVector{4, N0f16}
Vk.format_type(::Val{FORMAT_B16G16R16G16_422_UNORM}) = SVector{4, N0f16}

end
