module VulkanColorTypesExt

using Vulkan
using ColorTypes

# generated by `ext/generate_formats.jl`.

Vk.Format(::Type{RGB{Float16}}) = FORMAT_R16G16B16_SFLOAT
Vk.Format(::Type{RGBA{Float16}}) = FORMAT_R16G16B16A16_SFLOAT
Vk.Format(::Type{RGB{Float32}}) = FORMAT_R32G32B32_SFLOAT
Vk.Format(::Type{RGBA{Float32}}) = FORMAT_R32G32B32A32_SFLOAT
Vk.Format(::Type{RGB{Float64}}) = FORMAT_R64G64B64_SFLOAT
Vk.Format(::Type{RGBA{Float64}}) = FORMAT_R64G64B64A64_SFLOAT

Vk.format_type(::Val{FORMAT_R16G16B16_SFLOAT}) = RGB{Float16}
Vk.format_type(::Val{FORMAT_R16G16B16A16_SFLOAT}) = RGBA{Float16}
Vk.format_type(::Val{FORMAT_R32G32B32_SFLOAT}) = RGB{Float32}
Vk.format_type(::Val{FORMAT_R32G32B32A32_SFLOAT}) = RGBA{Float32}
Vk.format_type(::Val{FORMAT_R64G64B64_SFLOAT}) = RGB{Float64}
Vk.format_type(::Val{FORMAT_R64G64B64A64_SFLOAT}) = RGBA{Float64}

end
