module VulkanFixedPointNumbersExt

using Vulkan
using FixedPointNumbers

# generated by `ext/generate_formats.jl`.

Vk.Format(::Type{N0f8}) = FORMAT_R8_UNORM
Vk.Format(::Type{Q0f7}) = FORMAT_R8_SNORM
Vk.Format(::Type{N0f16}) = FORMAT_R16_UNORM
Vk.Format(::Type{Q0f15}) = FORMAT_R16_SNORM

Vk.format_type(::Val{FORMAT_R8_UNORM}) = N0f8
Vk.format_type(::Val{FORMAT_R8_SNORM}) = Q0f7
Vk.format_type(::Val{FORMAT_R16_UNORM}) = N0f16
Vk.format_type(::Val{FORMAT_R16_SNORM}) = Q0f15

end
