name: Documenter
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:

env:
  JULIA_DOCUMENTER_CI: ON

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: "1.9.3"
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@latest
      - name: Instantiate generator
        run: "julia --project=generator -e 'using Pkg; Pkg.instantiate()'"
      - uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
