name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.5', 'nightly']
        julia-arch: [x64, x86]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest
      - name: Run tests with xvfb
        run: |
          sudo apt-get install xvfb
          /usr/bin/xvfb-run -n 1 julia --project=. -e 'using Pkg; Pkg.test()'
